main = "Space"
exit = "Escape"
pause = "Backspace"
change_lang = "Control"
change_case = "Shift"

[time_to_long_press]
secs = 0
nanos = 100000000

[listen_delay]
secs = 0
nanos = 5000000

[accept_sequence_delay]
secs = 0
nanos = 750000000

# "ru" lang

[langs.ru.".-".Layout]
lower.Layout = "–∞"
[langs.ru."-...".Layout]
lower.Layout = "–±"
[langs.ru.".--".Layout]
lower.Layout = "–≤"
[langs.ru."--.".Layout]
lower.Layout = "–≥"
[langs.ru."-..".Layout]
lower.Layout = "–¥"
[langs.ru.".".Layout]
lower.Layout = "–µ"
[langs.ru."...-".Layout]
lower.Layout = "–∂"
[langs.ru."--..".Layout]
lower.Layout = "–∑"
[langs.ru."..".Layout]
lower.Layout = "–∏"
[langs.ru.".---".Layout]
lower.Layout = "–π"
[langs.ru."-.-".Layout]
lower.Layout = "–∫"
[langs.ru.".-..".Layout]
lower.Layout = "–ª"
[langs.ru."--".Layout]
lower.Layout = "–º"
[langs.ru."-.".Layout]
lower.Layout = "–Ω"
[langs.ru."---".Layout]
lower.Layout = "–æ"
[langs.ru.".--.".Layout]
lower.Layout = "–ø"
[langs.ru.".-.".Layout]
lower.Layout = "—Ä"
[langs.ru."...".Layout]
lower.Layout = "—Å"
[langs.ru."-".Layout]
lower.Layout = "—Ç"
[langs.ru."..-".Layout]
lower.Layout = "—É"
[langs.ru."..-.".Layout]
lower.Layout = "—Ñ"
[langs.ru."....".Layout]
lower.Layout = "—Ö"
[langs.ru."-.-.".Layout]
lower.Layout = "—Ü"
[langs.ru."---.".Layout]
lower.Layout = "—á"
[langs.ru."----".Layout]
lower.Layout = "—à"
[langs.ru."--.-".Layout]
lower.Layout = "—â"
[langs.ru.".--.-.".Layout]
lower.Layout = "—ä"
[langs.ru."-.--".Layout]
lower.Layout = "—ã"
[langs.ru."-..-".Layout]
lower.Layout = "—å"
[langs.ru."...-...".Layout]
lower.Layout = "—ç"
[langs.ru."..--".Layout]
lower.Layout = "—é"
[langs.ru.".-.-".Layout]
lower.Layout = "—è"

# "en" lang

[langs.en.".-".Layout]
lower.Layout = "a"
[langs.en."-...".Layout]
lower.Layout = "b"
[langs.en."-.-.".Layout]
lower.Layout = "c"
[langs.en."-..".Layout]
lower.Layout = "d"
[langs.en.".".Layout]
lower.Layout = "e"
[langs.en."..-.".Layout]
lower.Layout = "f"
[langs.en."--.".Layout]
lower.Layout = "g"
[langs.en."....".Layout]
lower.Layout = "h"
[langs.en."..".Layout]
lower.Layout = "i"
[langs.en.".---".Layout]
lower.Layout = "j"
[langs.en."-.-".Layout]
lower.Layout = "k"
[langs.en.".-..".Layout]
lower.Layout = "l"
[langs.en."--".Layout]
lower.Layout = "m"
[langs.en."-.".Layout]
lower.Layout = "n"
[langs.en."---".Layout]
lower.Layout = "o"
[langs.en.".--.".Layout]
lower.Layout = "p"
[langs.en."--.-".Layout]
lower.Layout = "q"
[langs.en.".-.".Layout]
lower.Layout = "r"
[langs.en."...".Layout]
lower.Layout = "s"
[langs.en."-".Layout]
lower.Layout = "t"
[langs.en."..-".Layout]
lower.Layout = "u"
[langs.en."...-".Layout]
lower.Layout = "v"
[langs.en.".--".Layout]
lower.Layout = "w"
[langs.en."-..-".Layout]
lower.Layout = "x"
[langs.en."-.--".Layout]
lower.Layout = "y"
[langs.en."--..".Layout]
lower.Layout = "z"

# "emoji" lang

[langs.emoji.".-".Layout]
lower.Layout = "üëç"
[langs.emoji."-...".Layout]
lower.Layout = "üëé"
[langs.emoji."-.-.".Layout]
lower.Layout = "üëå"
[langs.emoji."-..".Layout]
lower.Layout = "üëã"
[langs.emoji.".".Layout]
lower.Layout = "üëè"
[langs.emoji."..-.".Layout]
lower.Layout = "üëä"
[langs.emoji."--.".Layout]
lower.Layout = "üëÜ"
[langs.emoji."....".Layout]
lower.Layout = "üëá"
[langs.emoji."..".Layout]
lower.Layout = "üëà"
[langs.emoji.".---".Layout]
lower.Layout = "üëâ"
[langs.emoji."-.-".Layout]
lower.Layout = "üòà"

# "functional"

[functional."-.---"]
Code = "CapsLock"
[functional.".-.--"]
Code = "Backspace"
[functional.".--.-"]
Code = "F9"
[functional.".---.-"]
Code = "Accept"
[functional."--.--"]
Code = "Tab"
[functional."......".Layout]
lower.Layout = "."
[functional.".-.-.-".Layout]
lower.Layout = ","
[functional."..--..".Layout]
lower.Layout = "?"
[functional."-....-".Layout]
lower.Layout = "-"
[functional.".-..-.".Layout]
lower.Layout = "'"
[functional."-.-.-.".Layout]
lower.Layout = ";"
[functional."--..--".Layout]
lower.Layout = "!"
[[functional."-.--.-".Sequence]]
[functional."-.--.-".Sequence.lower]
Layout = "("
[[functional."-.--.-".Sequence]]
[functional."-.--.-".Sequence.lower]
Layout = ")"
[functional."---...".Layout]
lower.Layout = ":"
[functional.".-.-.".Layout]
lower.Layout = "+"
[functional."---.-".Layout]
lower.Layout = " "
[functional.".----".Layout]
lower.Layout = "1"
[functional."..---".Layout]
lower.Layout = "2"
[functional."...--".Layout]
lower.Layout = "3"
[functional."....-".Layout]
lower.Layout = "4"
[functional.".....".Layout]
lower.Layout = "5"
[functional."-....".Layout]
lower.Layout = "6"
[functional."--...".Layout]
lower.Layout = "7"
[functional."---..".Layout]
lower.Layout = "8"
[functional."----.".Layout]
lower.Layout = "9"
[functional."-----".Layout]
lower.Layout = "0"
